import type { CatalogItem, ItemCategory, ItemRarity } from "./types.ts";

type Seed = {
  name: string;
  category: ItemCategory;
  rarity: ItemRarity;
  baseCopper: number;
  service?: boolean;
};

const GOODS: Seed[] = [
  { name: "Barley loaf", category: "provisions", rarity: "common", baseCopper: 2 },
  { name: "Hard tack", category: "provisions", rarity: "common", baseCopper: 4 },
  { name: "Salt fish", category: "provisions", rarity: "common", baseCopper: 8 },
  { name: "Wheel of pale cheese", category: "provisions", rarity: "uncommon", baseCopper: 40 },
  { name: "Jar of honey", category: "provisions", rarity: "uncommon", baseCopper: 80 },
  { name: "Cask of cider", category: "provisions", rarity: "rare", baseCopper: 300 },
  { name: "Saffron thread", category: "provisions", rarity: "rare", baseCopper: 1500 },
  { name: "Bag of iron nails", category: "smith", rarity: "common", baseCopper: 5 },
  { name: "Iron hinge", category: "smith", rarity: "common", baseCopper: 10 },
  { name: "Hand axe", category: "smith", rarity: "uncommon", baseCopper: 200 },
  { name: "Ash spear", category: "smith", rarity: "uncommon", baseCopper: 100 },
  { name: "Mail shirt", category: "smith", rarity: "rare", baseCopper: 7500 },
  { name: "Steel longblade", category: "smith", rarity: "rare", baseCopper: 1500 },
  { name: "Bonded hinge", category: "smith", rarity: "magic", baseCopper: 20000 },
  { name: "Wool cloak", category: "cloth", rarity: "common", baseCopper: 50 },
  { name: "Linen shirt", category: "cloth", rarity: "common", baseCopper: 20 },
  { name: "Leather boots", category: "cloth", rarity: "uncommon", baseCopper: 100 },
  { name: "Fur mantle", category: "cloth", rarity: "rare", baseCopper: 2000 },
  { name: "Quiet boots", category: "cloth", rarity: "magic", baseCopper: 25000 },
  { name: "Bundle of willow", category: "apothecary", rarity: "common", baseCopper: 5 },
  { name: "Spirit of camphor", category: "apothecary", rarity: "common", baseCopper: 30 },
  { name: "Fever tea", category: "apothecary", rarity: "uncommon", baseCopper: 40 },
  { name: "Healer's kit", category: "apothecary", rarity: "uncommon", baseCopper: 500 },
  { name: "Tincture of poppy", category: "apothecary", rarity: "rare", baseCopper: 2000 },
  { name: "Mender's salve", category: "apothecary", rarity: "magic", baseCopper: 12000 },
  { name: "Night in the common room", category: "inn", rarity: "common", baseCopper: 8, service: true },
  { name: "Hot supper", category: "inn", rarity: "common", baseCopper: 8, service: true },
  { name: "Private room", category: "inn", rarity: "uncommon", baseCopper: 200, service: true },
  { name: "Bottle of the house red", category: "inn", rarity: "uncommon", baseCopper: 80 },
  { name: "Named vintage", category: "inn", rarity: "rare", baseCopper: 1500 },
  { name: "Lamp oil, flask", category: "general", rarity: "common", baseCopper: 4 },
  { name: "Hempen rope, 50 ft", category: "general", rarity: "common", baseCopper: 20 },
  { name: "Iron pot", category: "general", rarity: "common", baseCopper: 40 },
  { name: "Canvas tent", category: "general", rarity: "uncommon", baseCopper: 80 },
  { name: "Lock and key", category: "general", rarity: "uncommon", baseCopper: 100 },
  { name: "Spyglass", category: "general", rarity: "rare", baseCopper: 10000 },
  { name: "Odd tooth on a string", category: "curios", rarity: "common", baseCopper: 20 },
  { name: "Cracked cameo", category: "curios", rarity: "uncommon", baseCopper: 300 },
  { name: "Map with the edges burned", category: "curios", rarity: "rare", baseCopper: 2500 },
  { name: "Salt-circle chalk", category: "curios", rarity: "magic", baseCopper: 8000 },
  { name: "Ember clasp", category: "curios", rarity: "magic", baseCopper: 30000 },
  { name: "Pale-glass ward", category: "curios", rarity: "magic", baseCopper: 40000 },
  { name: "Nosebag of oats", category: "stable", rarity: "common", baseCopper: 8 },
  { name: "Day of stabling", category: "stable", rarity: "common", baseCopper: 20, service: true },
  { name: "Pack mule", category: "stable", rarity: "uncommon", baseCopper: 800 },
  { name: "War harness", category: "stable", rarity: "rare", baseCopper: 4000 },
  { name: "Riding horse", category: "stable", rarity: "rare", baseCopper: 7500 },
  { name: "Sheet of paper", category: "scribe", rarity: "common", baseCopper: 4 },
  { name: "Quill knife", category: "scribe", rarity: "common", baseCopper: 20 },
  { name: "Pot of ink", category: "scribe", rarity: "uncommon", baseCopper: 80 },
  { name: "Blank journal", category: "scribe", rarity: "uncommon", baseCopper: 200 },
  { name: "Survey map", category: "scribe", rarity: "rare", baseCopper: 3000 },
  { name: "Ink that will not fade", category: "scribe", rarity: "magic", baseCopper: 15000 },
  { name: "Copper ring", category: "jewels", rarity: "common", baseCopper: 50 },
  { name: "Silver brooch", category: "jewels", rarity: "uncommon", baseCopper: 800 },
  { name: "River pearl", category: "jewels", rarity: "rare", baseCopper: 5000 },
  { name: "Blank signet", category: "jewels", rarity: "rare", baseCopper: 8000 },
  { name: "True-weight chain", category: "jewels", rarity: "magic", baseCopper: 25000 },
  { name: "Tallow candle", category: "provisions", rarity: "common", baseCopper: 1 },
  { name: "Beeswax candle", category: "provisions", rarity: "common", baseCopper: 2 },
  { name: "Day's trail rations", category: "provisions", rarity: "common", baseCopper: 5 },
  { name: "Sack of flour", category: "provisions", rarity: "common", baseCopper: 8 },
  { name: "Dozen eggs", category: "provisions", rarity: "common", baseCopper: 4 },
  { name: "Sack of dried beans", category: "provisions", rarity: "common", baseCopper: 6 },
  { name: "Bunch of onions", category: "provisions", rarity: "common", baseCopper: 2 },
  { name: "Round of butter", category: "provisions", rarity: "common", baseCopper: 6 },
  { name: "Firewood, bundle", category: "provisions", rarity: "common", baseCopper: 2 },
  { name: "Cooking salt", category: "provisions", rarity: "common", baseCopper: 3 },
  { name: "Belt knife", category: "smith", rarity: "common", baseCopper: 20 },
  { name: "Whetstone", category: "smith", rarity: "common", baseCopper: 2 },
  { name: "Dozen arrows", category: "smith", rarity: "common", baseCopper: 10 },
  { name: "Horseshoe", category: "smith", rarity: "common", baseCopper: 8 },
  { name: "Wood axe", category: "smith", rarity: "common", baseCopper: 80 },
  { name: "Wool blanket", category: "cloth", rarity: "common", baseCopper: 30 },
  { name: "Leather belt", category: "cloth", rarity: "common", baseCopper: 10 },
  { name: "Pair of socks", category: "cloth", rarity: "common", baseCopper: 4 },
  { name: "Cloth cap", category: "cloth", rarity: "common", baseCopper: 8 },
  { name: "Waterskin", category: "general", rarity: "common", baseCopper: 10 },
  { name: "Backpack", category: "general", rarity: "common", baseCopper: 50 },
  { name: "Bedroll", category: "general", rarity: "common", baseCopper: 20 },
  { name: "Tinderbox", category: "general", rarity: "common", baseCopper: 30 },
  { name: "Empty sack", category: "general", rarity: "common", baseCopper: 1 },
  { name: "Wooden bowl", category: "general", rarity: "common", baseCopper: 2 },
  { name: "Iron spoon", category: "general", rarity: "common", baseCopper: 3 },
  { name: "Cake of soap", category: "general", rarity: "common", baseCopper: 2 },
  { name: "Ball of twine", category: "general", rarity: "common", baseCopper: 2 },
  { name: "Stick of chalk", category: "general", rarity: "common", baseCopper: 1 },
  { name: "Brass lantern", category: "general", rarity: "common", baseCopper: 100 },
  { name: "Iron piton", category: "general", rarity: "common", baseCopper: 2 },
  { name: "Wooden bucket", category: "general", rarity: "common", baseCopper: 5 },
  { name: "Needle and thread", category: "general", rarity: "common", baseCopper: 4 },
  { name: "Clean bandage", category: "apothecary", rarity: "common", baseCopper: 3 },
  { name: "Vial of vinegar", category: "apothecary", rarity: "common", baseCopper: 4 },
  { name: "Mug of ale", category: "inn", rarity: "common", baseCopper: 4, service: true },
  { name: "Breakfast", category: "inn", rarity: "common", baseCopper: 6, service: true },
  { name: "Armload of hay", category: "stable", rarity: "common", baseCopper: 3 },
  { name: "Stick of sealing wax", category: "scribe", rarity: "common", baseCopper: 8 },
];

export const CATALOG_REVISION = 2;

export const PREVIOUS_LIST: Record<string, number> = {
  "cat:hempen-rope-50-ft": 100,
  "cat:lamp-oil-flask": 10,
  "cat:iron-pot": 80,
  "cat:hand-axe": 500,
  "cat:night-in-the-common-room": 50,
  "cat:hot-supper": 15,
  "cat:canvas-tent": 200,
  "cat:lock-and-key": 400,
};

function slug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function starterCatalog(): CatalogItem[] {
  return GOODS.map((row) => ({
    id: `cat:${slug(row.name)}`,
    name: row.name,
    category: row.category,
    rarity: row.rarity,
    baseCopper: row.baseCopper,
    notes: "",
    origin: "stock",
    service: Boolean(row.service),
  }));
}
