import { commoditySchema, type Commodity } from "./trade-economy-schema.ts";

// Original Lootsplit homebrew templates. Prices are editable references, not official D&D prices.
const goods: [string, string, Commodity["category"], number, number, string][] = [
  ["wheat", "Wheat", "provisions", 100, 50, "50 lb sack"],
  ["barley", "Barley", "provisions", 80, 50, "50 lb sack"],
  ["oats", "Oats", "provisions", 75, 50, "50 lb sack"],
  ["rice", "Rice", "provisions", 200, 50, "50 lb sack"],
  ["flour", "Flour", "provisions", 150, 25, "25 lb sack"],
  ["salt", "Salt", "provisions", 250, 10, "10 lb sack"],
  ["honey", "Honey", "provisions", 300, 5, "5 lb jar"],
  ["dried-fruit", "Dried fruit", "provisions", 150, 5, "5 lb bundle"],
  ["salted-fish", "Salted fish", "provisions", 200, 10, "10 lb crate"],
  ["cooking-oil", "Cooking oil", "provisions", 200, 8, "1 gallon jar"],
  ["pepper", "Pepper", "provisions", 2000, 1, "1 lb pouch"],
  ["cinnamon", "Cinnamon", "provisions", 3000, 1, "1 lb pouch"],
  ["iron-ore", "Iron ore", "smith", 150, 25, "25 lb sack"],
  ["iron-ingots", "Iron ingots", "smith", 1000, 10, "10 lb bundle"],
  ["copper-ingots", "Copper ingots", "smith", 500, 10, "10 lb bundle"],
  ["tin-ingots", "Tin ingots", "smith", 600, 10, "10 lb bundle"],
  ["steel-ingots", "Steel ingots", "smith", 2000, 10, "10 lb bundle"],
  ["silver-bullion", "Silver bullion", "smith", 500, 1, "1 lb bar"],
  ["gold-bullion", "Gold bullion", "smith", 5000, 1, "1 lb bar"],
  ["coal", "Coal", "smith", 200, 25, "25 lb sack"],
  ["mithral", "Mithral ingots", "smith", 50000, 1, "1 lb bar"],
  ["adamantine", "Adamantine ingots", "smith", 100000, 1, "1 lb bar"],
  ["wool", "Raw wool", "cloth", 200, 10, "10 lb bale"],
  ["linen", "Linen cloth", "cloth", 500, 3, "10 yard roll"],
  ["cotton", "Cotton cloth", "cloth", 400, 3, "10 yard roll"],
  ["silk", "Silk cloth", "cloth", 5000, 2, "10 yard roll"],
  ["leather", "Tanned leather", "cloth", 1000, 5, "hide"],
  ["furs", "Furs", "cloth", 1500, 5, "bundle"],
  ["dye", "Cloth dye", "cloth", 500, 2, "jar"],
  ["healing-herbs", "Medicinal herbs", "apothecary", 500, 1, "1 lb bundle"],
  ["alchemical-salts", "Alchemical salts", "apothecary", 1000, 1, "1 lb jar"],
  ["sulfur", "Sulfur", "apothecary", 500, 1, "1 lb pouch"],
  ["quicksilver", "Quicksilver", "apothecary", 2000, 1, "sealed 1 lb flask"],
  ["night-bloom", "Night-bloom petals", "apothecary", 2500, 0.25, "sealed pouch"],
  ["mandrake", "Mandrake root", "apothecary", 1500, 1, "root"],
  ["ale", "Ale", "inn", 500, 40, "5 gallon keg"],
  ["wine", "Wine", "inn", 1000, 40, "5 gallon keg"],
  ["spirits", "Distilled spirits", "inn", 1500, 8, "1 gallon jug"],
  ["timber", "Building timber", "general", 500, 50, "50 lb bundle"],
  ["hardwood", "Seasoned hardwood", "general", 1000, 50, "50 lb bundle"],
  ["stone", "Dressed stone", "general", 300, 50, "50 lb crate"],
  ["clay", "Potter's clay", "general", 100, 25, "25 lb sack"],
  ["glass", "Glass blanks", "general", 1000, 10, "10 lb crate"],
  ["beeswax", "Beeswax", "general", 300, 5, "5 lb block"],
  ["resin", "Tree resin", "general", 200, 5, "5 lb jar"],
  ["dragon-scales", "Dragon scales", "curios", 10000, 1, "1 lb bundle"],
  ["wyvern-venom", "Wyvern venom", "curios", 25000, 0.25, "sealed vial"],
  ["phoenix-ash", "Phoenix ash", "curios", 50000, 0.25, "sealed vial"],
  ["ghost-orchid", "Ghost orchid", "curios", 5000, 0.25, "bloom"],
  ["elemental-crystal", "Elemental crystal", "curios", 10000, 1, "crystal"],
  ["enchanted-resin", "Enchanted resin", "curios", 7500, 1, "1 lb jar"],
  ["hay", "Hay", "stable", 100, 50, "50 lb bale"],
  ["animal-feed", "Animal feed", "stable", 150, 25, "25 lb sack"],
  ["parchment", "Parchment", "scribe", 1000, 2, "20 sheet bundle"],
  ["paper", "Paper", "scribe", 500, 2, "20 sheet bundle"],
  ["ink", "Writing ink", "scribe", 1000, 0.25, "bottle"],
  ["arcane-ink", "Arcane ink", "scribe", 10000, 0.25, "bottle"],
  ["quartz", "Quartz", "jewels", 500, 1, "1 lb parcel"],
  ["amber", "Amber", "jewels", 2500, 1, "1 lb parcel"],
  ["gem-rough", "Uncut gemstones", "jewels", 10000, 1, "1 lb parcel"],
];

export const STARTER_COMMODITIES: Commodity[] = goods.map(
  ([key, name, category, baseCopper, weight, unit]) =>
    commoditySchema.parse({
      id: `starter.${key}`,
      name,
      category,
      baseCopper,
      weight,
      unit,
      active: true,
      description: `Trade goods supplied as one ${unit}. Lootsplit homebrew reference value; the DM defines availability, quality and any special properties.`,
    }),
);
