/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PartyRouteImport } from './routes/party'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as ReadArticleIdRouteImport } from './routes/read.$articleId'
import { Route as ShopShopIdRouteImport } from './routes/shop.$shopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadArticleIdRoute = ReadArticleIdRouteImport.update({
  id: '/read/$articleId',
  path: '/read/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/market': typeof MarketRoute
  '/party': typeof PartyRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$articleId': typeof ReadArticleIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/market': typeof MarketRoute
  '/party': typeof PartyRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$articleId': typeof ReadArticleIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/market': typeof MarketRoute
  '/party': typeof PartyRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$articleId': typeof ReadArticleIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/catalog'
    | '/favorites'
    | '/market'
    | '/party'
    | '/settings'
    | '/share'
    | '/book/$bookId'
    | '/read/$articleId'
    | '/shop/$shopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/catalog'
    | '/favorites'
    | '/market'
    | '/party'
    | '/settings'
    | '/share'
    | '/book/$bookId'
    | '/read/$articleId'
    | '/shop/$shopId'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/catalog'
    | '/favorites'
    | '/market'
    | '/party'
    | '/settings'
    | '/share'
    | '/book/$bookId'
    | '/read/$articleId'
    | '/shop/$shopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  CatalogRoute: typeof CatalogRoute
  FavoritesRoute: typeof FavoritesRoute
  MarketRoute: typeof MarketRoute
  PartyRoute: typeof PartyRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ReadArticleIdRoute: typeof ReadArticleIdRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$articleId': {
      id: '/read/$articleId'
      path: '/read/$articleId'
      fullPath: '/read/$articleId'
      preLoaderRoute: typeof ReadArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  CatalogRoute: CatalogRoute,
  FavoritesRoute: FavoritesRoute,
  MarketRoute: MarketRoute,
  PartyRoute: PartyRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  BookBookIdRoute: BookBookIdRoute,
  ReadArticleIdRoute: ReadArticleIdRoute,
  ShopShopIdRoute: ShopShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
