/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PartyRouteImport } from './routes/party'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as DownloadAndroidRouteImport } from './routes/download.android'
import { Route as ReadArticleIdRouteImport } from './routes/read.$articleId'
import { Route as ShopShopIdRouteImport } from './routes/shop.$shopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadAndroidRoute = DownloadAndroidRouteImport.update({
  id: '/download/android',
  path: '/download/android',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadArticleIdRoute = ReadArticleIdRouteImport.update({
  id: '/read/$articleId',
  path: '/read/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/donate': typeof DonateRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/market': typeof MarketRoute
  '/party': typeof PartyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/updates': typeof UpdatesRoute
  '/welcome': typeof WelcomeRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/download/android': typeof DownloadAndroidRoute
  '/read/$articleId': typeof ReadArticleIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/donate': typeof DonateRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/market': typeof MarketRoute
  '/party': typeof PartyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/updates': typeof UpdatesRoute
  '/welcome': typeof WelcomeRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/download/android': typeof DownloadAndroidRoute
  '/read/$articleId': typeof ReadArticleIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/donate': typeof DonateRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/market': typeof MarketRoute
  '/party': typeof PartyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/updates': typeof UpdatesRoute
  '/welcome': typeof WelcomeRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/download/android': typeof DownloadAndroidRoute
  '/read/$articleId': typeof ReadArticleIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/books'
    | '/catalog'
    | '/donate'
    | '/downloads'
    | '/favorites'
    | '/help'
    | '/market'
    | '/party'
    | '/resources'
    | '/settings'
    | '/share'
    | '/updates'
    | '/welcome'
    | '/book/$bookId'
    | '/download/android'
    | '/read/$articleId'
    | '/shop/$shopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/books'
    | '/catalog'
    | '/donate'
    | '/downloads'
    | '/favorites'
    | '/help'
    | '/market'
    | '/party'
    | '/resources'
    | '/settings'
    | '/share'
    | '/updates'
    | '/welcome'
    | '/book/$bookId'
    | '/download/android'
    | '/read/$articleId'
    | '/shop/$shopId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/books'
    | '/catalog'
    | '/donate'
    | '/downloads'
    | '/favorites'
    | '/help'
    | '/market'
    | '/party'
    | '/resources'
    | '/settings'
    | '/share'
    | '/updates'
    | '/welcome'
    | '/book/$bookId'
    | '/download/android'
    | '/read/$articleId'
    | '/shop/$shopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BooksRoute: typeof BooksRoute
  CatalogRoute: typeof CatalogRoute
  DonateRoute: typeof DonateRoute
  DownloadsRoute: typeof DownloadsRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  MarketRoute: typeof MarketRoute
  PartyRoute: typeof PartyRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  UpdatesRoute: typeof UpdatesRoute
  WelcomeRoute: typeof WelcomeRoute
  BookBookIdRoute: typeof BookBookIdRoute
  DownloadAndroidRoute: typeof DownloadAndroidRoute
  ReadArticleIdRoute: typeof ReadArticleIdRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/android': {
      id: '/download/android'
      path: '/download/android'
      fullPath: '/download/android'
      preLoaderRoute: typeof DownloadAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$articleId': {
      id: '/read/$articleId'
      path: '/read/$articleId'
      fullPath: '/read/$articleId'
      preLoaderRoute: typeof ReadArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BooksRoute: BooksRoute,
  CatalogRoute: CatalogRoute,
  DonateRoute: DonateRoute,
  DownloadsRoute: DownloadsRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  MarketRoute: MarketRoute,
  PartyRoute: PartyRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  UpdatesRoute: UpdatesRoute,
  WelcomeRoute: WelcomeRoute,
  BookBookIdRoute: BookBookIdRoute,
  DownloadAndroidRoute: DownloadAndroidRoute,
  ReadArticleIdRoute: ReadArticleIdRoute,
  ShopShopIdRoute: ShopShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
