import type { ResourcePack } from "../resource-packs.ts";
export const resourcePackFixture: ResourcePack = {
  format: "lootsplit.resource-pack",
  version: 1,
  id: "synthetic-marsh",
  revision: "1",
  title: "Synthetic Marsh References",
  description: "Disposable synthetic records for import verification.",
  attribution: "Lootsplit test fixture; original synthetic content.",
  entries: [
    {
      id: "reed-guardian",
      kind: "creature",
      name: "Reed Guardian",
      text: "Reed Guardian\nArmor Class 14\nHit Points 22\nChallenge 1 (200 XP)\nActions\nReed Lash. Synthetic action.\nSalvage\nReed charm requires DM review.",
      stats: { ac: 14, hp: 22, cr: 1, xp: 200, initiativeBonus: 2 },
      tags: ["construct", "marsh"],
      warnings: [],
      sources: [{ book: "Synthetic Marsh", pdfPage: 12, printedPage: "8" }],
    },
    {
      id: "charm",
      kind: "item",
      name: "Reed Charm",
      text: "A synthetic charm. No source sale price.",
      category: "curios",
      rarity: "common",
      baseCopper: null,
      tags: [],
      warnings: ["Sale price is not supplied."],
      sources: [{ book: "Synthetic Marsh", pdfPage: 12, printedPage: "8" }],
    },
    {
      id: "marsh",
      kind: "location",
      name: "Synthetic Marsh",
      locationKind: "region",
      parentId: null,
      text: "Synthetic region.",
      tags: [],
      warnings: [],
      sources: [{ book: "Synthetic Marsh", pdfPage: 3, printedPage: null }],
    },
    {
      id: "reed-port",
      kind: "location",
      name: "Reed Port",
      locationKind: "city",
      parentId: "marsh",
      text: "Synthetic city.",
      tags: [],
      warnings: [],
      sources: [{ book: "Synthetic Marsh", pdfPage: 3, printedPage: null }],
    },
    {
      id: "reed-shop",
      kind: "shop",
      name: "Reed Workshop",
      parentId: "reed-port",
      text: "Synthetic shop reference.",
      tags: [],
      warnings: [],
      sources: [{ book: "Synthetic Marsh", pdfPage: 4, printedPage: null }],
    },
    {
      id: "reed-keeper",
      kind: "npc",
      name: "Reed Keeper",
      parentId: "reed-port",
      text: "Synthetic NPC reference.",
      tags: [],
      warnings: [],
      sources: [{ book: "Synthetic Marsh", pdfPage: 4, printedPage: null }],
    },
  ],
};
